export type MunicipioSalamanca = {
  readonly codigoIne: string;
  readonly digitoControl: string;
  readonly nombre: string;
};

export const FUENTE_MUNICIPIOS_SALAMANCA = {
  organismo: "Instituto Nacional de Estadistica",
  referencia: "Relacion de municipios y codigos a 1 de enero de 2026",
  url: "https://www.ine.es/daco/daco42/codmun/26codmun.xlsx",
} as const;

export const MUNICIPIOS_SALAMANCA: readonly MunicipioSalamanca[] = [
  { codigoIne: "37001", digitoControl: "6", nombre: "Abusejo" },
  { codigoIne: "37002", digitoControl: "1", nombre: "Agallas" },
  { codigoIne: "37003", digitoControl: "7", nombre: "Ahigal de los Aceiteros" },
  { codigoIne: "37004", digitoControl: "2", nombre: "Ahigal de Villarino" },
  { codigoIne: "37005", digitoControl: "5", nombre: "Alameda de Gardón, La" },
  { codigoIne: "37006", digitoControl: "8", nombre: "Alamedilla, La" },
  { codigoIne: "37007", digitoControl: "4", nombre: "Alaraz" },
  { codigoIne: "37008", digitoControl: "0", nombre: "Alba de Tormes" },
  { codigoIne: "37009", digitoControl: "3", nombre: "Alba de Yeltes" },
  { codigoIne: "37010", digitoControl: "7", nombre: "Alberca, La" },
  { codigoIne: "37011", digitoControl: "4", nombre: "Alberguería de Argañán, La" },
  { codigoIne: "37012", digitoControl: "9", nombre: "Alconada" },
  { codigoIne: "37015", digitoControl: "3", nombre: "Aldea del Obispo" },
  { codigoIne: "37013", digitoControl: "5", nombre: "Aldeacipreste" },
  { codigoIne: "37014", digitoControl: "0", nombre: "Aldeadávila de la Ribera" },
  { codigoIne: "37016", digitoControl: "6", nombre: "Aldealengua" },
  { codigoIne: "37017", digitoControl: "2", nombre: "Aldeanueva de Figueroa" },
  { codigoIne: "37018", digitoControl: "8", nombre: "Aldeanueva de la Sierra" },
  { codigoIne: "37019", digitoControl: "1", nombre: "Aldearrodrigo" },
  { codigoIne: "37020", digitoControl: "5", nombre: "Aldearrubia" },
  { codigoIne: "37021", digitoControl: "2", nombre: "Aldeaseca de Alba" },
  { codigoIne: "37022", digitoControl: "7", nombre: "Aldeaseca de la Frontera" },
  { codigoIne: "37023", digitoControl: "3", nombre: "Aldeatejada" },
  { codigoIne: "37024", digitoControl: "8", nombre: "Aldeavieja de Tormes" },
  { codigoIne: "37025", digitoControl: "1", nombre: "Aldehuela de la Bóveda" },
  { codigoIne: "37026", digitoControl: "4", nombre: "Aldehuela de Yeltes" },
  { codigoIne: "37027", digitoControl: "0", nombre: "Almenara de Tormes" },
  { codigoIne: "37028", digitoControl: "6", nombre: "Almendra" },
  { codigoIne: "37029", digitoControl: "9", nombre: "Anaya de Alba" },
  { codigoIne: "37030", digitoControl: "3", nombre: "Añover de Tormes" },
  { codigoIne: "37031", digitoControl: "0", nombre: "Arabayona de Mógica" },
  { codigoIne: "37032", digitoControl: "5", nombre: "Arapiles" },
  { codigoIne: "37033", digitoControl: "1", nombre: "Arcediano" },
  { codigoIne: "37034", digitoControl: "6", nombre: "Arco, El" },
  { codigoIne: "37035", digitoControl: "9", nombre: "Armenteros" },
  { codigoIne: "37037", digitoControl: "8", nombre: "Atalaya, La" },
  { codigoIne: "37038", digitoControl: "4", nombre: "Babilafuente" },
  { codigoIne: "37039", digitoControl: "7", nombre: "Bañobárez" },
  { codigoIne: "37040", digitoControl: "1", nombre: "Barbadillo" },
  { codigoIne: "37041", digitoControl: "8", nombre: "Barbalos" },
  { codigoIne: "37042", digitoControl: "3", nombre: "Barceo" },
  { codigoIne: "37044", digitoControl: "4", nombre: "Barruecopardo" },
  { codigoIne: "37045", digitoControl: "7", nombre: "Bastida, La" },
  { codigoIne: "37046", digitoControl: "0", nombre: "Béjar" },
  { codigoIne: "37047", digitoControl: "6", nombre: "Beleña" },
  { codigoIne: "37049", digitoControl: "5", nombre: "Bermellar" },
  { codigoIne: "37050", digitoControl: "8", nombre: "Berrocal de Huebra" },
  { codigoIne: "37051", digitoControl: "5", nombre: "Berrocal de Salvatierra" },
  { codigoIne: "37052", digitoControl: "0", nombre: "Boada" },
  { codigoIne: "37054", digitoControl: "1", nombre: "Bodón, El" },
  { codigoIne: "37055", digitoControl: "4", nombre: "Bogajo" },
  { codigoIne: "37056", digitoControl: "7", nombre: "Bouza, La" },
  { codigoIne: "37057", digitoControl: "3", nombre: "Bóveda del Río Almar" },
  { codigoIne: "37058", digitoControl: "9", nombre: "Brincones" },
  { codigoIne: "37059", digitoControl: "2", nombre: "Buenamadre" },
  { codigoIne: "37060", digitoControl: "6", nombre: "Buenavista" },
  { codigoIne: "37061", digitoControl: "3", nombre: "Cabaco, El" },
  { codigoIne: "37063", digitoControl: "4", nombre: "Cabeza de Béjar, La" },
  { codigoIne: "37065", digitoControl: "2", nombre: "Cabeza del Caballo" },
  { codigoIne: "37062", digitoControl: "8", nombre: "Cabezabellosa de la Calzada" },
  { codigoIne: "37067", digitoControl: "1", nombre: "Cabrerizos" },
  { codigoIne: "37068", digitoControl: "7", nombre: "Cabrillas" },
  { codigoIne: "37069", digitoControl: "0", nombre: "Calvarrasa de Abajo" },
  { codigoIne: "37070", digitoControl: "4", nombre: "Calvarrasa de Arriba" },
  { codigoIne: "37071", digitoControl: "1", nombre: "Calzada de Béjar, La" },
  { codigoIne: "37072", digitoControl: "6", nombre: "Calzada de Don Diego" },
  { codigoIne: "37073", digitoControl: "2", nombre: "Calzada de Valdunciel" },
  { codigoIne: "37074", digitoControl: "7", nombre: "Campillo de Azaba" },
  { codigoIne: "37077", digitoControl: "9", nombre: "Campo de Peñaranda, El" },
  { codigoIne: "37078", digitoControl: "5", nombre: "Candelario" },
  { codigoIne: "37079", digitoControl: "8", nombre: "Canillas de Abajo" },
  { codigoIne: "37080", digitoControl: "2", nombre: "Cantagallo" },
  { codigoIne: "37081", digitoControl: "9", nombre: "Cantalapiedra" },
  { codigoIne: "37082", digitoControl: "4", nombre: "Cantalpino" },
  { codigoIne: "37083", digitoControl: "0", nombre: "Cantaracillo" },
  { codigoIne: "37085", digitoControl: "8", nombre: "Carbajosa de la Sagrada" },
  { codigoIne: "37086", digitoControl: "1", nombre: "Carpio de Azaba" },
  { codigoIne: "37087", digitoControl: "7", nombre: "Carrascal de Barregas" },
  { codigoIne: "37088", digitoControl: "3", nombre: "Carrascal del Obispo" },
  { codigoIne: "37089", digitoControl: "6", nombre: "Casafranca" },
  { codigoIne: "37090", digitoControl: "0", nombre: "Casas del Conde, Las" },
  { codigoIne: "37091", digitoControl: "7", nombre: "Casillas de Flores" },
  { codigoIne: "37092", digitoControl: "2", nombre: "Castellanos de Moriscos" },
  { codigoIne: "37185", digitoControl: "7", nombre: "Castellanos de Villiquera" },
  { codigoIne: "37096", digitoControl: "9", nombre: "Castillejo de Martín Viejo" },
  { codigoIne: "37097", digitoControl: "5", nombre: "Castraz" },
  { codigoIne: "37098", digitoControl: "1", nombre: "Cepeda" },
  { codigoIne: "37099", digitoControl: "4", nombre: "Cereceda de la Sierra" },
  { codigoIne: "37100", digitoControl: "8", nombre: "Cerezal de Peñahorcada" },
  { codigoIne: "37101", digitoControl: "5", nombre: "Cerralbo" },
  { codigoIne: "37102", digitoControl: "0", nombre: "Cerro, El" },
  { codigoIne: "37103", digitoControl: "6", nombre: "Cespedosa de Tormes" },
  { codigoIne: "37114", digitoControl: "9", nombre: "Chagarcía Medianero" },
  { codigoIne: "37104", digitoControl: "1", nombre: "Cilleros de la Bastida" },
  { codigoIne: "37106", digitoControl: "7", nombre: "Cipérez" },
  { codigoIne: "37107", digitoControl: "3", nombre: "Ciudad Rodrigo" },
  { codigoIne: "37108", digitoControl: "9", nombre: "Coca de Alba" },
  { codigoIne: "37109", digitoControl: "2", nombre: "Colmenar de Montemayor" },
  { codigoIne: "37110", digitoControl: "6", nombre: "Cordovilla" },
  { codigoIne: "37112", digitoControl: "8", nombre: "Cristóbal" },
  { codigoIne: "37113", digitoControl: "4", nombre: "Cubo de Don Sancho, El" },
  { codigoIne: "37115", digitoControl: "2", nombre: "Dios le Guarde" },
  { codigoIne: "37116", digitoControl: "5", nombre: "Doñinos de Ledesma" },
  { codigoIne: "37117", digitoControl: "1", nombre: "Doñinos de Salamanca" },
  { codigoIne: "37118", digitoControl: "7", nombre: "Éjeme" },
  { codigoIne: "37120", digitoControl: "4", nombre: "Encina de San Silvestre" },
  { codigoIne: "37119", digitoControl: "0", nombre: "Encina, La" },
  { codigoIne: "37121", digitoControl: "1", nombre: "Encinas de Abajo" },
  { codigoIne: "37122", digitoControl: "6", nombre: "Encinas de Arriba" },
  { codigoIne: "37123", digitoControl: "2", nombre: "Encinasola de los Comendadores" },
  { codigoIne: "37124", digitoControl: "7", nombre: "Endrinal" },
  { codigoIne: "37125", digitoControl: "0", nombre: "Escurial de la Sierra" },
  { codigoIne: "37126", digitoControl: "3", nombre: "Espadaña" },
  { codigoIne: "37127", digitoControl: "9", nombre: "Espeja" },
  { codigoIne: "37128", digitoControl: "5", nombre: "Espino de la Orbada" },
  { codigoIne: "37129", digitoControl: "8", nombre: "Florida de Liébana" },
  { codigoIne: "37130", digitoControl: "2", nombre: "Forfoleda" },
  { codigoIne: "37131", digitoControl: "9", nombre: "Frades de la Sierra" },
  { codigoIne: "37132", digitoControl: "4", nombre: "Fregeneda, La" },
  { codigoIne: "37133", digitoControl: "0", nombre: "Fresnedoso" },
  { codigoIne: "37134", digitoControl: "5", nombre: "Fresno Alhándiga" },
  { codigoIne: "37135", digitoControl: "8", nombre: "Fuente de San Esteban, La" },
  { codigoIne: "37136", digitoControl: "1", nombre: "Fuenteguinaldo" },
  { codigoIne: "37137", digitoControl: "7", nombre: "Fuenteliante" },
  { codigoIne: "37138", digitoControl: "3", nombre: "Fuenterroble de Salvatierra" },
  { codigoIne: "37139", digitoControl: "6", nombre: "Fuentes de Béjar" },
  { codigoIne: "37140", digitoControl: "0", nombre: "Fuentes de Oñoro" },
  { codigoIne: "37141", digitoControl: "7", nombre: "Gajates" },
  { codigoIne: "37142", digitoControl: "2", nombre: "Galindo y Perahuy" },
  { codigoIne: "37143", digitoControl: "8", nombre: "Galinduste" },
  { codigoIne: "37144", digitoControl: "3", nombre: "Galisancho" },
  { codigoIne: "37145", digitoControl: "6", nombre: "Gallegos de Argañán" },
  { codigoIne: "37146", digitoControl: "9", nombre: "Gallegos de Solmirón" },
  { codigoIne: "37147", digitoControl: "5", nombre: "Garcibuey" },
  { codigoIne: "37148", digitoControl: "1", nombre: "Garcihernández" },
  { codigoIne: "37149", digitoControl: "4", nombre: "Garcirrey" },
  { codigoIne: "37150", digitoControl: "7", nombre: "Gejuelo del Barro" },
  { codigoIne: "37151", digitoControl: "4", nombre: "Golpejas" },
  { codigoIne: "37152", digitoControl: "9", nombre: "Gomecello" },
  { codigoIne: "37154", digitoControl: "0", nombre: "Guadramiro" },
  { codigoIne: "37155", digitoControl: "3", nombre: "Guijo de Ávila" },
  { codigoIne: "37156", digitoControl: "6", nombre: "Guijuelo" },
  { codigoIne: "37157", digitoControl: "2", nombre: "Herguijuela de Ciudad Rodrigo" },
  { codigoIne: "37158", digitoControl: "8", nombre: "Herguijuela de la Sierra" },
  { codigoIne: "37159", digitoControl: "1", nombre: "Herguijuela del Campo" },
  { codigoIne: "37160", digitoControl: "5", nombre: "Hinojosa de Duero" },
  { codigoIne: "37161", digitoControl: "2", nombre: "Horcajo de Montemayor" },
  { codigoIne: "37162", digitoControl: "7", nombre: "Horcajo Medianero" },
  { codigoIne: "37163", digitoControl: "3", nombre: "Hoya, La" },
  { codigoIne: "37164", digitoControl: "8", nombre: "Huerta" },
  { codigoIne: "37165", digitoControl: "1", nombre: "Iruelos" },
  { codigoIne: "37166", digitoControl: "4", nombre: "Ituero de Azaba" },
  { codigoIne: "37167", digitoControl: "0", nombre: "Juzbado" },
  { codigoIne: "37168", digitoControl: "6", nombre: "Lagunilla" },
  { codigoIne: "37169", digitoControl: "9", nombre: "Larrodrigo" },
  { codigoIne: "37170", digitoControl: "3", nombre: "Ledesma" },
  { codigoIne: "37171", digitoControl: "0", nombre: "Ledrada" },
  { codigoIne: "37172", digitoControl: "5", nombre: "Linares de Riofrío" },
  { codigoIne: "37173", digitoControl: "1", nombre: "Lumbrales" },
  { codigoIne: "37175", digitoControl: "9", nombre: "Machacón" },
  { codigoIne: "37174", digitoControl: "6", nombre: "Macotera" },
  { codigoIne: "37176", digitoControl: "2", nombre: "Madroñal" },
  { codigoIne: "37177", digitoControl: "8", nombre: "Maíllo, El" },
  { codigoIne: "37178", digitoControl: "4", nombre: "Malpartida" },
  { codigoIne: "37179", digitoControl: "7", nombre: "Mancera de Abajo" },
  { codigoIne: "37180", digitoControl: "1", nombre: "Manzano, El" },
  { codigoIne: "37181", digitoControl: "8", nombre: "Martiago" },
  { codigoIne: "37183", digitoControl: "9", nombre: "Martín de Yeltes" },
  { codigoIne: "37182", digitoControl: "3", nombre: "Martinamor" },
  { codigoIne: "37184", digitoControl: "4", nombre: "Masueco" },
  { codigoIne: "37186", digitoControl: "0", nombre: "Mata de Ledesma, La" },
  { codigoIne: "37187", digitoControl: "6", nombre: "Matilla de los Caños del Río" },
  { codigoIne: "37188", digitoControl: "2", nombre: "Maya, La" },
  { codigoIne: "37189", digitoControl: "5", nombre: "Membribe de la Sierra" },
  { codigoIne: "37190", digitoControl: "9", nombre: "Mieza" },
  { codigoIne: "37191", digitoControl: "6", nombre: "Milano, El" },
  { codigoIne: "37192", digitoControl: "1", nombre: "Miranda de Azán" },
  { codigoIne: "37193", digitoControl: "7", nombre: "Miranda del Castañar" },
  { codigoIne: "37194", digitoControl: "2", nombre: "Mogarraz" },
  { codigoIne: "37195", digitoControl: "5", nombre: "Molinillo" },
  { codigoIne: "37196", digitoControl: "8", nombre: "Monforte de la Sierra" },
  { codigoIne: "37197", digitoControl: "4", nombre: "Monleón" },
  { codigoIne: "37198", digitoControl: "0", nombre: "Monleras" },
  { codigoIne: "37199", digitoControl: "3", nombre: "Monsagro" },
  { codigoIne: "37200", digitoControl: "7", nombre: "Montejo" },
  { codigoIne: "37201", digitoControl: "4", nombre: "Montemayor del Río" },
  { codigoIne: "37202", digitoControl: "9", nombre: "Monterrubio de Armuña" },
  { codigoIne: "37203", digitoControl: "5", nombre: "Monterrubio de la Sierra" },
  { codigoIne: "37204", digitoControl: "0", nombre: "Morasverdes" },
  { codigoIne: "37205", digitoControl: "3", nombre: "Morille" },
  { codigoIne: "37206", digitoControl: "6", nombre: "Moríñigo" },
  { codigoIne: "37207", digitoControl: "2", nombre: "Moriscos" },
  { codigoIne: "37208", digitoControl: "8", nombre: "Moronta" },
  { codigoIne: "37209", digitoControl: "1", nombre: "Mozárbez" },
  { codigoIne: "37211", digitoControl: "2", nombre: "Narros de Matalayegua" },
  { codigoIne: "37213", digitoControl: "3", nombre: "Nava de Béjar" },
  { codigoIne: "37214", digitoControl: "8", nombre: "Nava de Francia" },
  { codigoIne: "37215", digitoControl: "1", nombre: "Nava de Sotrobal" },
  { codigoIne: "37212", digitoControl: "7", nombre: "Navacarros" },
  { codigoIne: "37216", digitoControl: "4", nombre: "Navales" },
  { codigoIne: "37217", digitoControl: "0", nombre: "Navalmoral de Béjar" },
  { codigoIne: "37218", digitoControl: "6", nombre: "Navamorales" },
  { codigoIne: "37219", digitoControl: "9", nombre: "Navarredonda de la Rinconada" },
  { codigoIne: "37221", digitoControl: "0", nombre: "Navasfrías" },
  { codigoIne: "37222", digitoControl: "5", nombre: "Negrilla de Palencia" },
  { codigoIne: "37223", digitoControl: "1", nombre: "Olmedo de Camaces" },
  { codigoIne: "37224", digitoControl: "6", nombre: "Orbada, La" },
  { codigoIne: "37225", digitoControl: "9", nombre: "Pajares de la Laguna" },
  { codigoIne: "37226", digitoControl: "2", nombre: "Palacios del Arzobispo" },
  { codigoIne: "37228", digitoControl: "4", nombre: "Palaciosrubios" },
  { codigoIne: "37229", digitoControl: "7", nombre: "Palencia de Negrilla" },
  { codigoIne: "37230", digitoControl: "1", nombre: "Parada de Arriba" },
  { codigoIne: "37231", digitoControl: "8", nombre: "Parada de Rubiales" },
  { codigoIne: "37232", digitoControl: "3", nombre: "Paradinas de San Juan" },
  { codigoIne: "37233", digitoControl: "9", nombre: "Pastores" },
  { codigoIne: "37234", digitoControl: "4", nombre: "Payo, El" },
  { codigoIne: "37235", digitoControl: "7", nombre: "Pedraza de Alba" },
  { codigoIne: "37236", digitoControl: "0", nombre: "Pedrosillo de Alba" },
  { codigoIne: "37237", digitoControl: "6", nombre: "Pedrosillo de los Aires" },
  { codigoIne: "37238", digitoControl: "2", nombre: "Pedrosillo el Ralo" },
  { codigoIne: "37239", digitoControl: "5", nombre: "Pedroso de la Armuña, El" },
  { codigoIne: "37240", digitoControl: "9", nombre: "Pelabravo" },
  { codigoIne: "37241", digitoControl: "6", nombre: "Pelarrodríguez" },
  { codigoIne: "37242", digitoControl: "1", nombre: "Pelayos" },
  { codigoIne: "37243", digitoControl: "7", nombre: "Peña, La" },
  { codigoIne: "37244", digitoControl: "2", nombre: "Peñacaballera" },
  { codigoIne: "37245", digitoControl: "5", nombre: "Peñaparda" },
  { codigoIne: "37246", digitoControl: "8", nombre: "Peñaranda de Bracamonte" },
  { codigoIne: "37247", digitoControl: "4", nombre: "Peñarandilla" },
  { codigoIne: "37248", digitoControl: "0", nombre: "Peralejos de Abajo" },
  { codigoIne: "37249", digitoControl: "3", nombre: "Peralejos de Arriba" },
  { codigoIne: "37250", digitoControl: "6", nombre: "Pereña de la Ribera" },
  { codigoIne: "37251", digitoControl: "3", nombre: "Peromingo" },
  { codigoIne: "37252", digitoControl: "8", nombre: "Pinedas" },
  { codigoIne: "37253", digitoControl: "4", nombre: "Pino de Tormes, El" },
  { codigoIne: "37254", digitoControl: "9", nombre: "Pitiegua" },
  { codigoIne: "37255", digitoControl: "2", nombre: "Pizarral" },
  { codigoIne: "37256", digitoControl: "5", nombre: "Poveda de las Cintas" },
  { codigoIne: "37257", digitoControl: "1", nombre: "Pozos de Hinojo" },
  { codigoIne: "37258", digitoControl: "7", nombre: "Puebla de Azaba" },
  { codigoIne: "37259", digitoControl: "0", nombre: "Puebla de San Medel" },
  { codigoIne: "37260", digitoControl: "4", nombre: "Puebla de Yeltes" },
  { codigoIne: "37261", digitoControl: "1", nombre: "Puente del Congosto" },
  { codigoIne: "37262", digitoControl: "6", nombre: "Puertas" },
  { codigoIne: "37263", digitoControl: "2", nombre: "Puerto de Béjar" },
  { codigoIne: "37264", digitoControl: "7", nombre: "Puerto Seguro" },
  { codigoIne: "37265", digitoControl: "0", nombre: "Rágama" },
  { codigoIne: "37266", digitoControl: "3", nombre: "Redonda, La" },
  { codigoIne: "37267", digitoControl: "9", nombre: "Retortillo" },
  { codigoIne: "37268", digitoControl: "5", nombre: "Rinconada de la Sierra, La" },
  { codigoIne: "37269", digitoControl: "8", nombre: "Robleda" },
  { codigoIne: "37270", digitoControl: "2", nombre: "Robliza de Cojos" },
  { codigoIne: "37271", digitoControl: "9", nombre: "Rollán" },
  { codigoIne: "37272", digitoControl: "4", nombre: "Saelices el Chico" },
  { codigoIne: "37273", digitoControl: "0", nombre: "Sagrada, La" },
  { codigoIne: "37303", digitoControl: "4", nombre: "Sahugo, El" },
  { codigoIne: "37274", digitoControl: "5", nombre: "Salamanca" },
  { codigoIne: "37275", digitoControl: "8", nombre: "Saldeana" },
  { codigoIne: "37276", digitoControl: "1", nombre: "Salmoral" },
  { codigoIne: "37277", digitoControl: "7", nombre: "Salvatierra de Tormes" },
  { codigoIne: "37278", digitoControl: "3", nombre: "San Cristóbal de la Cuesta" },
  { codigoIne: "37284", digitoControl: "3", nombre: "San Esteban de la Sierra" },
  { codigoIne: "37285", digitoControl: "6", nombre: "San Felices de los Gallegos" },
  { codigoIne: "37286", digitoControl: "9", nombre: "San Martín del Castañar" },
  { codigoIne: "37287", digitoControl: "5", nombre: "San Miguel de Valero" },
  { codigoIne: "37036", digitoControl: "2", nombre: "San Miguel del Robledo" },
  { codigoIne: "37288", digitoControl: "1", nombre: "San Morales" },
  { codigoIne: "37289", digitoControl: "4", nombre: "San Muñoz" },
  { codigoIne: "37291", digitoControl: "5", nombre: "San Pedro de Rozados" },
  { codigoIne: "37290", digitoControl: "8", nombre: "San Pedro del Valle" },
  { codigoIne: "37292", digitoControl: "0", nombre: "San Pelayo de Guareña" },
  { codigoIne: "37280", digitoControl: "0", nombre: "Sanchón de la Ribera" },
  { codigoIne: "37281", digitoControl: "7", nombre: "Sanchón de la Sagrada" },
  { codigoIne: "37282", digitoControl: "2", nombre: "Sanchotello" },
  { codigoIne: "37279", digitoControl: "6", nombre: "Sancti-Spíritus" },
  { codigoIne: "37283", digitoControl: "8", nombre: "Sando" },
  { codigoIne: "37293", digitoControl: "6", nombre: "Santa María de Sando" },
  { codigoIne: "37294", digitoControl: "1", nombre: "Santa Marta de Tormes" },
  { codigoIne: "37296", digitoControl: "7", nombre: "Santiago de la Puebla" },
  { codigoIne: "37297", digitoControl: "3", nombre: "Santibáñez de Béjar" },
  { codigoIne: "37298", digitoControl: "9", nombre: "Santibáñez de la Sierra" },
  { codigoIne: "37299", digitoControl: "2", nombre: "Santiz" },
  { codigoIne: "37300", digitoControl: "6", nombre: "Santos, Los" },
  { codigoIne: "37301", digitoControl: "3", nombre: "Sardón de los Frailes" },
  { codigoIne: "37302", digitoControl: "8", nombre: "Saucelle" },
  { codigoIne: "37304", digitoControl: "9", nombre: "Sepulcro-Hilario" },
  { codigoIne: "37305", digitoControl: "2", nombre: "Sequeros" },
  { codigoIne: "37306", digitoControl: "5", nombre: "Serradilla del Arroyo" },
  { codigoIne: "37307", digitoControl: "1", nombre: "Serradilla del Llano" },
  { codigoIne: "37309", digitoControl: "0", nombre: "Sierpe, La" },
  { codigoIne: "37310", digitoControl: "4", nombre: "Sieteiglesias de Tormes" },
  { codigoIne: "37311", digitoControl: "1", nombre: "Sobradillo" },
  { codigoIne: "37312", digitoControl: "6", nombre: "Sorihuela" },
  { codigoIne: "37313", digitoControl: "2", nombre: "Sotoserrano" },
  { codigoIne: "37314", digitoControl: "7", nombre: "Tabera de Abajo" },
  { codigoIne: "37315", digitoControl: "0", nombre: "Tala, La" },
  { codigoIne: "37316", digitoControl: "3", nombre: "Tamames" },
  { codigoIne: "37317", digitoControl: "9", nombre: "Tarazona de Guareña" },
  { codigoIne: "37318", digitoControl: "5", nombre: "Tardáguila" },
  { codigoIne: "37319", digitoControl: "8", nombre: "Tejado, El" },
  { codigoIne: "37320", digitoControl: "2", nombre: "Tejeda y Segoyuela" },
  { codigoIne: "37321", digitoControl: "9", nombre: "Tenebrón" },
  { codigoIne: "37322", digitoControl: "4", nombre: "Terradillos" },
  { codigoIne: "37323", digitoControl: "0", nombre: "Topas" },
  { codigoIne: "37324", digitoControl: "5", nombre: "Tordillos" },
  { codigoIne: "37325", digitoControl: "8", nombre: "Tornadizo, El" },
  { codigoIne: "37327", digitoControl: "7", nombre: "Torresmenudas" },
  { codigoIne: "37328", digitoControl: "3", nombre: "Trabanca" },
  { codigoIne: "37329", digitoControl: "6", nombre: "Tremedal de Tormes" },
  { codigoIne: "37330", digitoControl: "0", nombre: "Valdecarros" },
  { codigoIne: "37331", digitoControl: "7", nombre: "Valdefuentes de Sangusín" },
  { codigoIne: "37332", digitoControl: "2", nombre: "Valdehijaderos" },
  { codigoIne: "37333", digitoControl: "8", nombre: "Valdelacasa" },
  { codigoIne: "37334", digitoControl: "3", nombre: "Valdelageve" },
  { codigoIne: "37335", digitoControl: "6", nombre: "Valdelosa" },
  { codigoIne: "37336", digitoControl: "9", nombre: "Valdemierque" },
  { codigoIne: "37337", digitoControl: "5", nombre: "Valderrodrigo" },
  { codigoIne: "37338", digitoControl: "1", nombre: "Valdunciel" },
  { codigoIne: "37339", digitoControl: "4", nombre: "Valero" },
  { codigoIne: "37343", digitoControl: "6", nombre: "Vallejera de Riofrío" },
  { codigoIne: "37340", digitoControl: "8", nombre: "Valsalabroso" },
  { codigoIne: "37341", digitoControl: "5", nombre: "Valverde de Valdelacasa" },
  { codigoIne: "37342", digitoControl: "0", nombre: "Valverdón" },
  { codigoIne: "37344", digitoControl: "1", nombre: "Vecinos" },
  { codigoIne: "37345", digitoControl: "4", nombre: "Vega de Tirados" },
  { codigoIne: "37346", digitoControl: "7", nombre: "Veguillas, Las" },
  { codigoIne: "37347", digitoControl: "3", nombre: "Vellés, La" },
  { codigoIne: "37348", digitoControl: "9", nombre: "Ventosa del Río Almar" },
  { codigoIne: "37349", digitoControl: "2", nombre: "Vídola, La" },
  { codigoIne: "37351", digitoControl: "2", nombre: "Villaflores" },
  { codigoIne: "37352", digitoControl: "7", nombre: "Villagonzalo de Tormes" },
  { codigoIne: "37353", digitoControl: "3", nombre: "Villalba de los Llanos" },
  { codigoIne: "37354", digitoControl: "8", nombre: "Villamayor" },
  { codigoIne: "37355", digitoControl: "1", nombre: "Villanueva del Conde" },
  { codigoIne: "37356", digitoControl: "4", nombre: "Villar de Argañán" },
  { codigoIne: "37357", digitoControl: "0", nombre: "Villar de Ciervo" },
  { codigoIne: "37358", digitoControl: "6", nombre: "Villar de Gallimazo" },
  { codigoIne: "37359", digitoControl: "9", nombre: "Villar de la Yegua" },
  { codigoIne: "37360", digitoControl: "3", nombre: "Villar de Peralonso" },
  { codigoIne: "37361", digitoControl: "0", nombre: "Villar de Samaniego" },
  { codigoIne: "37362", digitoControl: "5", nombre: "Villares de la Reina" },
  { codigoIne: "37363", digitoControl: "1", nombre: "Villares de Yeltes" },
  { codigoIne: "37364", digitoControl: "6", nombre: "Villarino de los Aires" },
  { codigoIne: "37365", digitoControl: "9", nombre: "Villarmayor" },
  { codigoIne: "37366", digitoControl: "2", nombre: "Villarmuerto" },
  { codigoIne: "37367", digitoControl: "8", nombre: "Villasbuenas" },
  { codigoIne: "37368", digitoControl: "4", nombre: "Villasdardo" },
  { codigoIne: "37369", digitoControl: "7", nombre: "Villaseco de los Gamitos" },
  { codigoIne: "37370", digitoControl: "1", nombre: "Villaseco de los Reyes" },
  { codigoIne: "37371", digitoControl: "8", nombre: "Villasrubias" },
  { codigoIne: "37372", digitoControl: "3", nombre: "Villaverde de Guareña" },
  { codigoIne: "37373", digitoControl: "9", nombre: "Villavieja de Yeltes" },
  { codigoIne: "37374", digitoControl: "4", nombre: "Villoria" },
  { codigoIne: "37375", digitoControl: "7", nombre: "Villoruela" },
  { codigoIne: "37350", digitoControl: "5", nombre: "Vilvestre" },
  { codigoIne: "37376", digitoControl: "0", nombre: "Vitigudino" },
  { codigoIne: "37377", digitoControl: "6", nombre: "Yecla de Yeltes" },
  { codigoIne: "37378", digitoControl: "2", nombre: "Zamarra" },
  { codigoIne: "37379", digitoControl: "5", nombre: "Zamayón" },
  { codigoIne: "37380", digitoControl: "9", nombre: "Zarapicos" },
  { codigoIne: "37381", digitoControl: "6", nombre: "Zarza de Pumareda, La" },
  { codigoIne: "37382", digitoControl: "1", nombre: "Zorita de la Frontera" },
];

function nombreNatural(nombreOficial: string) {
  const partes = nombreOficial.match(/^(.*), (El|La|Los|Las)$/);
  return partes ? `${partes[2]} ${partes[1]}` : nombreOficial;
}

export const NOMBRES_MUNICIPIOS_SALAMANCA = MUNICIPIOS_SALAMANCA.map(({ nombre }) =>
  nombreNatural(nombre),
);
